// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {
  // From wrangler.jsonc `vars`
  SHOP: string;
  // Cloudflare secret (`wrangler secret put ...`) / local `.dev.vars`
  SHOPIFY_ADMIN_API_TOKEN: string;
}
